version: "3.8"

services:
  # Service untuk aplikasi web PHP
  web:
    build: .
    container_name: myopinion-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # Service untuk database MySQL
  db:
    image: mysql:5.7
    container_name: myopinion-db
    restart: always
    environment:
      MYSQL_DATABASE: myopinion_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  # Service untuk phpMyAdmin (opsional, untuk manajemen database)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myopinion-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db

volumes:
  db-data:
